LIKELIHOOD_OF_MOVE=0.2 # HOW LIKELY THE MONKEY IS TO MAKE A MOVE
LOSS_WEIGHT=.5 # WE PICK MATCHES WHERE THE TEAM LOSES WITH THIS WEIGHT
WIN_WEIGHT=.1 # WE PICK MATCHES WHERE THE TEAM WINS WITH THIS WEIGHT
SCALE_POINT_DIFF=0.05 # WE NEED TO SCALE THE POINT DIFFERENTIALS IN TO AN EXPONENTIAL SCALE TO CREATE WEIGHTS